# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kitchen_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

try:
    from PySide import QtCore, QtGui
except ImportError:
    from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Kitchen(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1193, 873)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayoutWidget = QtGui.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 1191, 861))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.time_lcd = QtGui.QLCDNumber(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_lcd.sizePolicy().hasHeightForWidth())
        self.time_lcd.setSizePolicy(sizePolicy)
        self.time_lcd.setObjectName(_fromUtf8("time_lcd"))
        self.gridLayout.addWidget(self.time_lcd, 1, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.search_le = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_le.sizePolicy().hasHeightForWidth())
        self.search_le.setSizePolicy(sizePolicy)
        self.search_le.setObjectName(_fromUtf8("search_le"))
        self.horizontalLayout_6.addWidget(self.search_le)
        self.go_bt = QtGui.QToolButton(self.gridLayoutWidget)
        self.go_bt.setObjectName(_fromUtf8("go_bt"))
        self.horizontalLayout_6.addWidget(self.go_bt)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.line_2 = QtGui.QFrame(self.gridLayoutWidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.cal_rad = QtGui.QRadioButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cal_rad.sizePolicy().hasHeightForWidth())
        self.cal_rad.setSizePolicy(sizePolicy)
        self.cal_rad.setChecked(True)
        self.cal_rad.setObjectName(_fromUtf8("cal_rad"))
        self.verticalLayout.addWidget(self.cal_rad)
        self.show_emp_rad = QtGui.QRadioButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_emp_rad.sizePolicy().hasHeightForWidth())
        self.show_emp_rad.setSizePolicy(sizePolicy)
        self.show_emp_rad.setObjectName(_fromUtf8("show_emp_rad"))
        self.verticalLayout.addWidget(self.show_emp_rad)
        self.show_rad = QtGui.QRadioButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_rad.sizePolicy().hasHeightForWidth())
        self.show_rad.setSizePolicy(sizePolicy)
        self.show_rad.setObjectName(_fromUtf8("show_rad"))
        self.verticalLayout.addWidget(self.show_rad)
        self.bought_rb = QtGui.QRadioButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bought_rb.sizePolicy().hasHeightForWidth())
        self.bought_rb.setSizePolicy(sizePolicy)
        self.bought_rb.setObjectName(_fromUtf8("bought_rb"))
        self.verticalLayout.addWidget(self.bought_rb)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.calculate_bt = QtGui.QPushButton(self.gridLayoutWidget)
        self.calculate_bt.setObjectName(_fromUtf8("calculate_bt"))
        self.verticalLayout.addWidget(self.calculate_bt)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 2, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.timer_dial = QtGui.QDial(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timer_dial.sizePolicy().hasHeightForWidth())
        self.timer_dial.setSizePolicy(sizePolicy)
        self.timer_dial.setMaximum(300)
        self.timer_dial.setObjectName(_fromUtf8("timer_dial"))
        self.horizontalLayout.addWidget(self.timer_dial)
        self.timer_lcd = QtGui.QLCDNumber(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timer_lcd.sizePolicy().hasHeightForWidth())
        self.timer_lcd.setSizePolicy(sizePolicy)
        self.timer_lcd.setObjectName(_fromUtf8("timer_lcd"))
        self.horizontalLayout.addWidget(self.timer_lcd)
        self.timer_bt = QtGui.QToolButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timer_bt.sizePolicy().hasHeightForWidth())
        self.timer_bt.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/aperture.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.timer_bt.setIcon(icon)
        self.timer_bt.setIconSize(QtCore.QSize(32, 32))
        self.timer_bt.setObjectName(_fromUtf8("timer_bt"))
        self.horizontalLayout.addWidget(self.timer_bt)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.cancel_bt = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_bt.sizePolicy().hasHeightForWidth())
        self.cancel_bt.setSizePolicy(sizePolicy)
        self.cancel_bt.setObjectName(_fromUtf8("cancel_bt"))
        self.horizontalLayout_3.addWidget(self.cancel_bt)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.calorie_lcd = QtGui.QLCDNumber(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calorie_lcd.sizePolicy().hasHeightForWidth())
        self.calorie_lcd.setSizePolicy(sizePolicy)
        self.calorie_lcd.setObjectName(_fromUtf8("calorie_lcd"))
        self.horizontalLayout_4.addWidget(self.calorie_lcd)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_7.addWidget(self.label_2)
        self.language_bt = QtGui.QToolButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.language_bt.sizePolicy().hasHeightForWidth())
        self.language_bt.setSizePolicy(sizePolicy)
        self.language_bt.setMaximumSize(QtCore.QSize(38, 34))
        self.language_bt.setObjectName(_fromUtf8("language_bt"))
        self.horizontalLayout_7.addWidget(self.language_bt)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_7)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 2, 1, 1)
        self.stuff_table = QtGui.QTableWidget(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stuff_table.sizePolicy().hasHeightForWidth())
        self.stuff_table.setSizePolicy(sizePolicy)
        self.stuff_table.setMaximumSize(QtCore.QSize(16777180, 16777215))
        self.stuff_table.setObjectName(_fromUtf8("stuff_table"))
        self.stuff_table.setColumnCount(0)
        self.stuff_table.setRowCount(0)
        self.gridLayout.addWidget(self.stuff_table, 3, 1, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.video_view = QtGui.QGraphicsView(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_view.sizePolicy().hasHeightForWidth())
        self.video_view.setSizePolicy(sizePolicy)
        self.video_view.setMinimumSize(QtCore.QSize(350, 192))
        self.video_view.setMaximumSize(QtCore.QSize(350, 192))
        self.video_view.setObjectName(_fromUtf8("video_view"))
        self.verticalLayout_2.addWidget(self.video_view)
        self.line = QtGui.QFrame(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(350, 3))
        self.line.setMaximumSize(QtCore.QSize(350, 3))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_2.addWidget(self.line)
        self.gloabal_tab = QtGui.QTabWidget(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gloabal_tab.sizePolicy().hasHeightForWidth())
        self.gloabal_tab.setSizePolicy(sizePolicy)
        self.gloabal_tab.setMinimumSize(QtCore.QSize(350, 542))
        self.gloabal_tab.setMaximumSize(QtCore.QSize(350, 542))
        self.gloabal_tab.setObjectName(_fromUtf8("gloabal_tab"))
        self.recipes_tab = QtGui.QWidget()
        self.recipes_tab.setObjectName(_fromUtf8("recipes_tab"))
        self.recipe_list = QtGui.QListWidget(self.recipes_tab)
        self.recipe_list.setGeometry(QtCore.QRect(0, 0, 341, 501))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recipe_list.sizePolicy().hasHeightForWidth())
        self.recipe_list.setSizePolicy(sizePolicy)
        self.recipe_list.setMaximumSize(QtCore.QSize(350, 501))
        self.recipe_list.setObjectName(_fromUtf8("recipe_list"))
        self.gloabal_tab.addTab(self.recipes_tab, _fromUtf8(""))
        self.weekly_tab = QtGui.QWidget()
        self.weekly_tab.setObjectName(_fromUtf8("weekly_tab"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.weekly_tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 341, 501))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gridLayoutWidget_2)
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.weekly_tw = QtGui.QTableWidget(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weekly_tw.sizePolicy().hasHeightForWidth())
        self.weekly_tw.setSizePolicy(sizePolicy)
        self.weekly_tw.setMinimumSize(QtCore.QSize(339, 459))
        self.weekly_tw.setMaximumSize(QtCore.QSize(339, 459))
        self.weekly_tw.setObjectName(_fromUtf8("weekly_tw"))
        self.weekly_tw.setColumnCount(0)
        self.weekly_tw.setRowCount(0)
        self.verticalLayout_3.addWidget(self.weekly_tw)
        self.clear_bt = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_bt.sizePolicy().hasHeightForWidth())
        self.clear_bt.setSizePolicy(sizePolicy)
        self.clear_bt.setObjectName(_fromUtf8("clear_bt"))
        self.verticalLayout_3.addWidget(self.clear_bt)
        self.gloabal_tab.addTab(self.weekly_tab, _fromUtf8(""))
        self.playlist_tab = QtGui.QWidget()
        self.playlist_tab.setObjectName(_fromUtf8("playlist_tab"))
        self.playlist_lw = QtGui.QListWidget(self.playlist_tab)
        self.playlist_lw.setGeometry(QtCore.QRect(0, 0, 341, 501))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playlist_lw.sizePolicy().hasHeightForWidth())
        self.playlist_lw.setSizePolicy(sizePolicy)
        self.playlist_lw.setObjectName(_fromUtf8("playlist_lw"))
        self.gloabal_tab.addTab(self.playlist_tab, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.gloabal_tab)
        self.gridLayout.addLayout(self.verticalLayout_2, 3, 2, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.stop_bt = QtGui.QToolButton(self.gridLayoutWidget)
        self.stop_bt.setObjectName(_fromUtf8("stop_bt"))
        self.horizontalLayout_5.addWidget(self.stop_bt)
        self.prev_bt = QtGui.QToolButton(self.gridLayoutWidget)
        self.prev_bt.setObjectName(_fromUtf8("prev_bt"))
        self.horizontalLayout_5.addWidget(self.prev_bt)
        self.play_pause_bt = QtGui.QToolButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play_pause_bt.sizePolicy().hasHeightForWidth())
        self.play_pause_bt.setSizePolicy(sizePolicy)
        self.play_pause_bt.setMaximumSize(QtCore.QSize(40, 40))
        self.play_pause_bt.setIconSize(QtCore.QSize(32, 32))
        self.play_pause_bt.setObjectName(_fromUtf8("play_pause_bt"))
        self.horizontalLayout_5.addWidget(self.play_pause_bt)
        self.next_bt = QtGui.QToolButton(self.gridLayoutWidget)
        self.next_bt.setObjectName(_fromUtf8("next_bt"))
        self.horizontalLayout_5.addWidget(self.next_bt)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 2, 1, 1)

        self.retranslateUi(Form)
        self.gloabal_tab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.search_le.setPlaceholderText(_translate("Form", "Search ...", None))
        self.go_bt.setText(_translate("Form", "...", None))
        self.cal_rad.setText(_translate("Form", "Calories summation", None))
        self.show_emp_rad.setText(_translate("Form", "Show stock (empty things)", None))
        self.show_rad.setText(_translate("Form", "show stock (existing things)", None))
        self.bought_rb.setText(_translate("Form", "Bought goods", None))
        self.calculate_bt.setText(_translate("Form", "Calculate calories", None))
        self.timer_bt.setText(_translate("Form", "...", None))
        self.cancel_bt.setText(_translate("Form", "Cancel", None))
        self.label.setText(_translate("Form", "kcal", None))
        self.label_2.setText(_translate("Form", "set Language:", None))
        self.language_bt.setText(_translate("Form", "en", None))
        self.gloabal_tab.setTabText(self.gloabal_tab.indexOf(self.recipes_tab), _translate("Form", "Recipes", None))
        self.clear_bt.setText(_translate("Form", "Wipe List", None))
        self.gloabal_tab.setTabText(self.gloabal_tab.indexOf(self.weekly_tab), _translate("Form", "Weekly Rota", None))
        self.gloabal_tab.setTabText(self.gloabal_tab.indexOf(self.playlist_tab), _translate("Form", "Playlist", None))
        self.stop_bt.setText(_translate("Form", "...", None))
        self.prev_bt.setText(_translate("Form", "...", None))
        self.play_pause_bt.setText(_translate("Form", "...", None))
        self.next_bt.setText(_translate("Form", "...", None))

