# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_NewRecipe(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(856, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 841, 641))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.adress_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adress_edit.sizePolicy().hasHeightForWidth())
        self.adress_edit.setSizePolicy(sizePolicy)
        self.adress_edit.setObjectName("adress_edit")
        self.horizontalLayout.addWidget(self.adress_edit)
        self.start_search_button = QtWidgets.QToolButton(self.verticalLayoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start_search_button.setIcon(icon)
        self.start_search_button.setIconSize(QtCore.QSize(32, 32))
        self.start_search_button.setObjectName("start_search_button")
        self.horizontalLayout.addWidget(self.start_search_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.rec_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rec_tab.sizePolicy().hasHeightForWidth())
        self.rec_tab.setSizePolicy(sizePolicy)
        self.rec_tab.setObjectName("rec_tab")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.rec_tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-1, -1, 821, 506))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pos1_rb = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.pos1_rb.setObjectName("pos1_rb")
        self.horizontalLayout_2.addWidget(self.pos1_rb)
        self.pos2_rb = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.pos2_rb.setObjectName("pos2_rb")
        self.horizontalLayout_2.addWidget(self.pos2_rb)
        self.pos3_rb = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.pos3_rb.setObjectName("pos3_rb")
        self.horizontalLayout_2.addWidget(self.pos3_rb)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.rec_text = QtWidgets.QTextBrowser(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rec_text.sizePolicy().hasHeightForWidth())
        self.rec_text.setSizePolicy(sizePolicy)
        self.rec_text.setObjectName("rec_text")
        self.horizontalLayout_5.addWidget(self.rec_text)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.portion_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portion_edit.sizePolicy().hasHeightForWidth())
        self.portion_edit.setSizePolicy(sizePolicy)
        self.portion_edit.setObjectName("portion_edit")
        self.verticalLayout_4.addWidget(self.portion_edit)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.prep_check = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.prep_check.setText("")
        self.prep_check.setObjectName("prep_check")
        self.horizontalLayout_6.addWidget(self.prep_check)
        self.prep_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prep_edit.sizePolicy().hasHeightForWidth())
        self.prep_edit.setSizePolicy(sizePolicy)
        self.prep_edit.setObjectName("prep_edit")
        self.horizontalLayout_6.addWidget(self.prep_edit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cook_check = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.cook_check.setText("")
        self.cook_check.setObjectName("cook_check")
        self.horizontalLayout_7.addWidget(self.cook_check)
        self.cook_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cook_edit.sizePolicy().hasHeightForWidth())
        self.cook_edit.setSizePolicy(sizePolicy)
        self.cook_edit.setObjectName("cook_edit")
        self.horizontalLayout_7.addWidget(self.cook_edit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_4.addWidget(self.line_3)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.baking_check = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.baking_check.setText("")
        self.baking_check.setObjectName("baking_check")
        self.horizontalLayout_8.addWidget(self.baking_check)
        self.baking_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baking_edit.sizePolicy().hasHeightForWidth())
        self.baking_edit.setSizePolicy(sizePolicy)
        self.baking_edit.setObjectName("baking_edit")
        self.horizontalLayout_8.addWidget(self.baking_edit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_4.addWidget(self.line_4)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.rest_check = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.rest_check.setText("")
        self.rest_check.setObjectName("rest_check")
        self.horizontalLayout_9.addWidget(self.rest_check)
        self.rest_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rest_edit.sizePolicy().hasHeightForWidth())
        self.rest_edit.setSizePolicy(sizePolicy)
        self.rest_edit.setObjectName("rest_edit")
        self.horizontalLayout_9.addWidget(self.rest_edit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.line_5 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_4.addWidget(self.line_5)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.cool_check = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.cool_check.setText("")
        self.cool_check.setObjectName("cool_check")
        self.horizontalLayout_10.addWidget(self.cool_check)
        self.cool_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cool_edit.sizePolicy().hasHeightForWidth())
        self.cool_edit.setSizePolicy(sizePolicy)
        self.cool_edit.setObjectName("cool_edit")
        self.horizontalLayout_10.addWidget(self.cool_edit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.line_6 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_4.addWidget(self.line_6)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.freeze_check = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.freeze_check.setText("")
        self.freeze_check.setObjectName("freeze_check")
        self.horizontalLayout_11.addWidget(self.freeze_check)
        self.freeze_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.freeze_edit.sizePolicy().hasHeightForWidth())
        self.freeze_edit.setSizePolicy(sizePolicy)
        self.freeze_edit.setObjectName("freeze_edit")
        self.horizontalLayout_11.addWidget(self.freeze_edit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.rec_tab, "")
        self.ingr_tab = QtWidgets.QWidget()
        self.ingr_tab.setObjectName("ingr_tab")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.ingr_tab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(-1, -1, 831, 501))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pos1_irb = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.pos1_irb.setObjectName("pos1_irb")
        self.horizontalLayout_4.addWidget(self.pos1_irb)
        self.pos2_irb = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.pos2_irb.setObjectName("pos2_irb")
        self.horizontalLayout_4.addWidget(self.pos2_irb)
        self.pos3_irb = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.pos3_irb.setObjectName("pos3_irb")
        self.horizontalLayout_4.addWidget(self.pos3_irb)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.ingr_text = QtWidgets.QTextBrowser(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ingr_text.sizePolicy().hasHeightForWidth())
        self.ingr_text.setSizePolicy(sizePolicy)
        self.ingr_text.setObjectName("ingr_text")
        self.verticalLayout_3.addWidget(self.ingr_text)
        self.tabWidget.addTab(self.ingr_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cancel_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_3.addWidget(self.cancel_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.name_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.name_edit.setObjectName("name_edit")
        self.horizontalLayout_3.addWidget(self.name_edit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.save_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_3.addWidget(self.save_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 856, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.adress_edit.setPlaceholderText(_translate("MainWindow", "Insert the recipe link here"))
        self.start_search_button.setText(_translate("MainWindow", "..."))
        self.pos1_rb.setText(_translate("MainWindow", "Option 1"))
        self.pos2_rb.setText(_translate("MainWindow", "Option 2"))
        self.pos3_rb.setText(_translate("MainWindow", "Option 3"))
        self.portion_edit.setPlaceholderText(_translate("MainWindow", "Number of Portions"))
        self.label.setText(_translate("MainWindow", "Preparation Time"))
        self.prep_edit.setPlaceholderText(_translate("MainWindow", "None"))
        self.label_2.setText(_translate("MainWindow", "Cooking Time"))
        self.cook_edit.setPlaceholderText(_translate("MainWindow", "None"))
        self.label_3.setText(_translate("MainWindow", "Baking Time"))
        self.baking_edit.setPlaceholderText(_translate("MainWindow", "None"))
        self.label_4.setText(_translate("MainWindow", "Resting Time"))
        self.rest_edit.setPlaceholderText(_translate("MainWindow", "None"))
        self.label_5.setText(_translate("MainWindow", "Cooling Time"))
        self.cool_edit.setPlaceholderText(_translate("MainWindow", "None"))
        self.label_6.setText(_translate("MainWindow", "Freezing Time"))
        self.freeze_edit.setPlaceholderText(_translate("MainWindow", "None"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rec_tab), _translate("MainWindow", "Recipe"))
        self.pos1_irb.setText(_translate("MainWindow", "Option 1"))
        self.pos2_irb.setText(_translate("MainWindow", "Option 2"))
        self.pos3_irb.setText(_translate("MainWindow", "Option 3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ingr_tab), _translate("MainWindow", "Ingredients"))
        self.cancel_button.setText(_translate("MainWindow", "Cancel"))
        self.name_edit.setPlaceholderText(_translate("MainWindow", "Enter the recipe Name"))
        self.save_button.setText(_translate("MainWindow", "Save"))

